DELIMITER $$

CREATE PROCEDURE INSERIR_TURMA(
	IN P_ALUNO NVARCHAR(11), IN P_PROFESSOR NVARCHAR(11)
)
BEGIN
	DECLARE ALUNO INT;
	DECLARE PROFESSOR INT;
    
    IF( (SELECT COUNT(IDALUNO) FROM ALUNO WHERE CPF = P_ALUNO > 0) 
		OR (SELECT IDPROFESSOR FROM PROFESSOR WHERE CPF = P_PROFESSOR > 0) 
	) THEN
    
		SET ALUNO =(SELECT IDALUNO FROM ALUNO WHERE CPF = P_ALUNO);
		SET PROFESSOR = (SELECT IDPROFESSOR FROM PROFESSOR WHERE CPF = P_PROFESSOR);
		INSERT INTO TURMA VALUES(default, ALUNO, PROFESSOR);
	ELSE 
		SELECT 'ALUNO OU PROFESSOR NÃO ENCONTRADO!';
    END IF;
END $$

CALL INSERIR_TURMA('00000030022', '00000202005');

SELECT * FROM TURMA;