DELIMITER $$

CREATE PROCEDURE CADASTRO_ALUNO
(
	IN P_NOMEALUNO nvarchar(45), IN P_NASCIMENTO DATE, IN P_CPF CHAR(11), IN P_RG CHAR(9),
    IN P_SEXO CHAR(1), IN P_NACIONALIDADE NVARCHAR(35), IN P_TELEFONE CHAR(10), IN P_CELULAR CHAR(11),
    IN P_EMAIL NVARCHAR(40), IN P_RUA NVARCHAR(60), IN P_CEP CHAR(8), IN P_NUMERO SMALLINT, IN P_CIDADE NVARCHAR(40),
	IN P_ESTADO CHAR(2)
)
BEGIN
    DECLARE CONTATOID INT;
    DECLARE ENDERECOID INT;
    DECLARE CONTAGEM_EMAIL INT;
    DECLARE CONTAGEM_CELULAR INT;
    
    SET CONTAGEM_EMAIL = (SELECT COUNT(IDCONTATOS) FROM CONTATOS WHERE EMAIL = P_EMAIL);
    SET CONTAGEM_CELULAR = (SELECT COUNT(IDCONTATOS) FROM CONTATOS WHERE CELULAR = P_CELULAR);
    
    INSERT INTO ENDERECO VALUES(DEFAULT, P_RUA, P_CEP, P_NUMERO, P_CIDADE, P_ESTADO);
    SET ENDERECOID = (SELECT MAX(IDENDERECO) FROM ENDERECO);    
   
   IF((CONTAGEM_EMAIL > 0) OR (CONTAGEM_CELULAR > 0)) THEN
		SELECT 'EMAIL OU CELULAR EXISTENTE!!!!';
   ELSE
		INSERT INTO CONTATOS VALUES(DEFAULT,P_TELEFONE,P_CELULAR,P_EMAIL);
		SET CONTATOID = (SELECT MAX(IDCONTATOS) FROM CONTATOS); 
	END IF;
   
	INSERT INTO ALUNO VALUES(
	DEFAULT, P_NOMEALUNO, P_NASCIMENTO, P_CPF, P_RG, P_SEXO, P_NACIONALIDADE, CONTATOID, ENDERECOID);    
    
END $$
DELIMITER ;

CALL CADASTRO_ALUNO (
'Aluno de tal2', '2010-01-05', '00000030022', '200000122', 'F', 'Brasil', '1222200029',1230000225,
'aluno22@email.com', 'Rua de Tal 2', '00000236', 022, 'São Paulo', 'sp'
);

select * from aluno;