CREATE DATABASE ESCOLA;
USE ESCOLA;

CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY auto_increment,
    RUA NVARCHAR(60) NOT NULL,
    CEP CHAR(8) NOT NULL,
    NUMERO SMALLINT NOT NULL,
    CIDADE NVARCHAR(40) NOT NULL,
    ESTADO CHAR(2) NOT NULL
);

CREATE TABLE CONTATOS(
	IDCONTATOS INT PRIMARY KEY auto_increment,
    TELEFONE CHAR(10),
    CELULAR CHAR(11) UNIQUE,
    EMAIL NVARCHAR(40) NOT NULL UNIQUE
   
);

CREATE TABLE MATERIA(
	IDMATERIA INT PRIMARY KEY auto_increment,
    NOMEMATERIA NVARCHAR(45) NOT NULL UNIQUE
);

CREATE TABLE PROFESSOR(
	IDPROFESSOR INT PRIMARY KEY auto_increment,
    NOMEPROFESSOR NVARCHAR(45) NOT NULL,
    NASCIMENTO DATE NOT NULL,
    CPF CHAR(11) NOT NULL UNIQUE,
    RG CHAR(9) NOT NULL,
    SEXO CHAR(1),
    NACIONALIDADE NVARCHAR(35) DEFAULT 'BRASIL',
    CHECK(SEXO IN ('F','M')),
    ID_CONTATOS INT NOT NULL, 
    ID_ENDERECO INT NOT NULL, 
    ID_MATERIA INT NOT NULL, 
    FOREIGN KEY (ID_CONTATOS) REFERENCES CONTATOS(IDCONTATOS),
    FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECO(IDENDERECO),
    FOREIGN KEY (ID_MATERIA) REFERENCES MATERIA(IDMATERIA)
    ON DELETE CASCADE
	ON UPDATE CASCADE
);

CREATE TABLE ALUNO (
	IDALUNO INT PRIMARY KEY auto_increment,
    NOMEALUNO NVARCHAR(45) NOT NULL,
    NASCIMENTO DATE NOT NULL,
    CPF CHAR(11) NOT NULL UNIQUE,
    RG CHAR(9) NOT NULL,
    SEXO CHAR(1),
    NACIONALIDADE NVARCHAR(35) DEFAULT 'BRASIL',
    CHECK(SEXO IN ('F','M')),
	ID_CONTATOS INT NOT NULL, 
    ID_ENDERECO INT NOT NULL, 
	FOREIGN KEY (ID_CONTATOS) REFERENCES CONTATOS(IDCONTATOS),
    FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECO(IDENDERECO)
);

CREATE TABLE TURMA(
	IDTURMA INT PRIMARY KEY auto_increment,
    ID_ALUNO INT NOT NULL,
    ID_PROFESSOR INT NOT NULL,
    FOREIGN KEY (ID_ALUNO) REFERENCES ALUNO(IDALUNO),
    FOREIGN KEY (ID_PROFESSOR) REFERENCES PROFESSOR(IDPROFESSOR),
    
);

/*----*/
SET SQL_SAFE_UPDATES = 0; /*DESATIVAR MODO DE SEGURANÇA*/



