SELECT * FROM PROFESSOR;

CREATE VIEW VW_PROFESSOR
AS
SELECT P.NOMEPROFESSOR, P.NASCIMENTO, P.CPF, P.RG, P.SEXO, P.NACIONALIDADE, 
C.TELEFONE, C.CELULAR, C.EMAIL, E.RUA, E.CEP, E.NUMERO, E.CIDADE, E.ESTADO, M.NOMEMATERIA FROM professor AS P
INNER JOIN contatos AS C
ON P.ID_CONTATOS = C.IDCONTATOS
INNER JOIN ENDERECO AS E
ON P.ID_ENDERECO = E.IDENDERECO
INNER JOIN MATERIA AS M
ON P.ID_MATERIA = M.IDMATERIA;

select * from vw_professor;