SELECT * FROM ALUNO;

CREATE VIEW VW_ALUNO
AS
SELECT A.NOMEALUNO, A.NASCIMENTO, A.CPF, A.RG, A.SEXO, A.NACIONALIDADE, 
C.TELEFONE, C.CELULAR, C.EMAIL, E.RUA, E.CEP, E.NUMERO, E.CIDADE, E.ESTADO FROM ALUNO AS A
INNER JOIN contatos AS C
ON A.ID_CONTATOS = C.IDCONTATOS
INNER JOIN ENDERECO AS E
ON A.ID_ENDERECO = E.IDENDERECO;

select * from vw_ALUNO;