SELECT * FROM TURMA;

CREATE VIEW VW_TURMA
AS
SELECT A.NOMEALUNO AS ALUNO, P.NOMEPROFESSOR AS PROFESSOR, M.NOMEMATERIA AS MATERIA FROM TURMA AS T
INNER JOIN ALUNO AS A
ON T.ID_ALUNO = A.IDALUNO
INNER JOIN PROFESSOR AS P
ON T.ID_PROFESSOR = P.IDPROFESSOR
INNER JOIN materia AS M
ON M.IDMATERIA = P.ID_MATERIA;

SELECT * FROM VW_TURMA